version: '2.3'

services:
    laravel:
        build: ./laravel
        container_name: laravel
        volumes:
            - ./laravel:/var/www
        networks:
            - app-network
        depends_on: 
            mysql:
                condition: service_healthy

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./laravel:/var/www
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"  
        volumes:
            - ./mysql/dbdata:/var/lib/mysql          
        environment:
            - MYSQL_DATABASE=laravel    
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
        healthcheck:
            test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']    
            interval: 10s
            timeout: 10s
            retries: 4

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379    
        networks:
            - app-network
            
networks:
    app-network:
        driver: bridge